### ISSUE TITLE
Gate Sequencer Reset Mode does not save with patch

### ISSUE THREAD

**Issue by Torinbob** [LomasModules/LomasModules#11]
I set the Reset mode to 'Instant' as this seems to be required to get the first note to trigger and for things to be in time, but after saving, when I reopen the patch, (or just restart VCV after quitting) then the reset mode defaults back to 'Next Clock Input'.

It's a very nice Gate sequencer -  would be great if there was some way to add probability per step.

**Comment by LomasModules** [comment]
Fixed.

Programming per step probability is easy. But I can't think of a nice way to edit it without adding knobs to the module.

**Comment by Torinbob** [comment]
Thanks for fixing!

Just a suggestion re. probability - there's space below the pattern select section where you could add one knob and a 3 character display to show the probability percentage. Double click a gate button to enter probability mode, and the probability for that step shows in the display and can be changed with the knob?

**Comment by LomasModules** [comment]
Double clicks are more complex that just click and hold. I would have to use a state machine or something like that. And I think all the inpust will have to be delayed. Is not an option.

The space there was used at one point to have 3 CV knobs. And you could hold a step to load the CV of that step. Something like a elektron machine. But the workflow was clunky. I would like to implement something like that in the future if I can find a good workflow.
