### ISSUE TITLE
Heavy clicking and audio output breaking regularly.

### ISSUE THREAD

**Issue by LomasModules** [LomasModules/LomasModules#12]
This isn't fixed for me. Still same issues as before: Heavy clicking and audio output breaking regularly. I used the 1.0.8. json file from here.

_Originally posted by @Hawgk in https://github.com/LomasModules/LomasModules/issues/8#issuecomment-564897098_

**Comment by LomasModules** [comment]
I am not able to reproduce this. It works fine on my computer. Can somebody with the problem send a patch to test it?

**Comment by Hawgk** [comment]
[testpatch.zip](https://github.com/LomasModules/LomasModules/files/3991451/testpatch.zip)
Here you go. Although the patch probably won't work as you don't have the samples. But what breaks my audio guarantied is this sample: 
[sample.zip](https://github.com/LomasModules/LomasModules/files/3991454/sample.zip)
To reproduce set the bpm to 135 and as soon as I change the pitch to a higher note it breaks my audio every time.

**Comment by LomasModules** [comment]
I have loaded the sample with the last version and it works fine for me. Can you try the v1.0.9 version and see if it fixes it?

**Comment by Hawgk** [comment]
It's fixed for me. Thanks a lot for your hard work and dedication!
