### ISSUE TITLE
How to turn off the linked syncing in gate sequencer? 

### ISSUE THREAD

**Issue by spectromas** [LomasModules/LomasModules#15]
Is there a way to turn off the module clock syncing when more than one are next to each other? I would have thought that if you feed them different clocks then they would play from those clocks but this doesn't seem to be the case, the modules all lock to one of the clocks. 

Am I missing something or can this be a feature request, an option to not sync with next module?

**Comment by LomasModules** [comment]
There is no such option. I just leave a space when I need it. I can make it so when you plug in the clock input it uses that clock not the linked clock.

**Comment by spectromas** [comment]
Cool, yeah I think that would make more sense. Thanks!

**Comment by LomasModules** [comment]
Done
