### ISSUE TITLE
Will you be updating LomasModules for Rack v2?

### ISSUE THREAD

**Issue by Torinbob** [LomasModules/LomasModules#19]
Hi,

Was just wondering if you are planning to update your modules for Rack v2? The v2 source has been published and the v2 SDK is available just in case you weren't aware of that yet. 

I find both your modules to be pretty indispensable in my patches so I very much hope so :)

cheers,
Steve

**Comment by jaffasplaffa** [comment]
+1

It would be awesome to have your modules available in VCV2. 

Your sampler is magnifique ;)

**Comment by netboy3** [comment]
Attached is a zip file with pre-built plugins for rack V2. Please remember to unzip first, then install the version corresponding to your platform.

[LomasModules-2.0.0.zip](https://github.com/LomasModules/LomasModules/files/7678939/LomasModules-2.0.0.zip)

Please post any V2 migration related issues to this thread.

**Comment by LomasModules** [comment]
Module has been update to v2. Thanks netboy2 and ATorinbob for the pr.
