### ISSUE TITLE
AdvancedSampler tooltip omission

### ISSUE THREAD

**Issue by Coirt** [LomasModules/LomasModules#2]
Incorrect time reported from the tooltip values on attack and decay. The lambda value needs to be convert back to milliseconds.
https://github.com/LomasModules/LomasModules/blob/master/src/AdvancedSampler.cpp#L69

`configParam(ATTACK_PARAM, 0.0f, 1.f, 0.0f, "Attack", " ms", LAMBDA_BASE, MIN_TIME * 1000);`

**Comment by LomasModules** [comment]
In my test the times work fine. When the tooltip says 1000ms it takes 1 second tod fully decay. 100ms takes 100ms and so on.

Can you provide more information? What exactly is wrong?

**Comment by LomasModules** [comment]
Now i see what you mean.

The default parameter of displayMultiplier is 1, that is why is working. Is there any benefit of using MIN_TIME * 1000 instead of the default parameter?

**Comment by Coirt** [comment]
I think it converts it back to time from samples, but I could be wrong.
