### ISSUE TITLE
Feature request - Input for turning loop on/off!

### ISSUE THREAD

**Issue by jaffasplaffa** [LomasModules/LomasModules#21]
Hey :) 

I really love this sampler, it's really good, the best sampler I found in VCV yet!

One thing I'd like to suggest is an input for the loop on/off function. 

I can do something similar, by using the EOC output and route it back to the trigger input, but that makes the envelope not work as (I think) is intended, as it's triggered every time the trigger input is high. 

So the envelope won't really fade out the same way as if you use the build in loop button. That's where the loop on/off input comes in, so you can turn the loop function on/off using a gate or a midi controller or what ever :) 

I hope it makes sense!

Thanks in advance, Jakob

**Comment by LomasModules** [comment]
Maybe you can do the same other way, multiple samplers or an external ADRS.
I am not sure about more inputs. The panel has already too many things going on.

**Comment by jaffasplaffa** [comment]
That's not an option, cause I like to turn the loop function on/off dynamically by using triggers/gates. I'd have to manually be able to turn the loop on from outside the module.

IMO design is secondary to audio related functions, since it is an audio instrument. I think the function is more important than the design.

Anyway, no worries, I will probably make my own version.
