### ISSUE TITLE
License clarification (plugin.json conflicts with LICENSE file)

### ISSUE THREAD

**Issue by falkTX** [LomasModules/LomasModules#23]
Hi there.
This is a little strange and awkward.

The `LICENSE` file on this repo is a copy of the GPLv3, but `plugin.json` says the license is `BSD`.
Which one is correct?

**Comment by falkTX** [comment]
Maybe when 8e529163b8fd205639e5db08c699c23a93abd460 was pushed, you forgot the change the license in `plugin.json`?
I suggest `GPL-3.0-or-later` so the source code remains compatible with GPLv4 whenever that comes out.

**Comment by LomasModules** [comment]
Thanks,

I think I forgot to change it when VCV itself switched licenses. It is GPL-3.0-or-later now
