### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [LomasModules/LomasModules#26]
Just a quick question, as I don't see it mentioned anywhere.
The project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?

The readme states:

> All copyright, credit and ownership of these modules remains with the original developer Guillermo Moreno.

But these are not license terms.
Should I ask Guillermo to clarify on that, or do you know?

Thanks!

**Comment by LomasModules** [comment]
The code and graphics are GPL-3.0 licensed, you can use both.

I own all the copyright of the code and art.

**Comment by falkTX** [comment]
Ok fair enough, that is all I wanted to know.
Thanks!
