### ISSUE TITLE
Advanced Sampler tune

### ISSUE THREAD

**Issue by Coirt** [LomasModules/LomasModules#3]
The Tune of a sample can go beyond 20kHz and below 10Hz. I'd recommend putting a clamp on the Tune input as sending a uni-polar signal such as an LFO makes the tune input not very useful for that type of LFO signal, however it might be useful to have a sample go into LFO rate (such as low bit LFO Wave from a sample). You could put a clamp here so the Tune will stay in hearing range.

https://github.com/LomasModules/LomasModules/blob/master/src/AdvancedSampler.cpp#L196

I would probably do this instead:
```
+++float tuneInput = clamp(inputs[TUNE_INPUT].getVoltage(), -9.f, 6.f);
---float freq = std::pow(2, (params[TUNE_PARAM].getValue() + inputs[TUNE_INPUT].getVoltage() * 12) / 12.0f);
+++float freq = std::pow(2, (params[TUNE_PARAM].getValue() + tuneInput * 12) / 12.f);
```

clamaped `6.f` max will keep it in hearing range while still being audible (high frequency).

**Comment by LomasModules** [comment]
Done. 

Thanks!

**Comment by Coirt** [comment]
@LomasModules 

Actually, forgot to take into account the upper limit of tune knob so

`float tuneInput = clamp(inputs[TUNE_INPUT].getVoltage(), -9.f, 4.f);`

Which will stop it going past 20kHz when tune knob is at +24 semi' 

~~This should stop it going past 5.5v/oct which can cause issues with a sample infinitely spiking.~~

**Comment by Coirt** [comment]
Did not properly test that last night get a `NAN` when the tune input goes past the clamp `rescale()` might better suit.

**Comment by Coirt** [comment]
Clamping the output `out` further down I think will fix that bug I introduced

```
float out = frame.samples[0] * env_.process(args.sampleTime) * 10;
+++out = clamp(out, -10.f, 10.f);
outputs[AUDIO_OUTPUT].setVoltage(out);
```
