### ISSUE TITLE
When trying to load a new sample into Lomas VCV crashed

### ISSUE THREAD

**Issue by markireland** [LomasModules/LomasModules#5]
When trying to load a new sample into Lomas VCV crashed and on restart the file had the name of the previous save.

**Comment by LomasModules** [comment]
I will look into it. But i need more details. What OS are you using? Was it moving the sampe knob or with the load button? Where you modulating any inputs?

> on restart the file had the name of the previous save.

Did the module load with the old sample? That is normal behavior, it prevents rack crashing again.

**Comment by LomasModules** [comment]
Now the sampler does not crash when opening a new folder.
