### ISSUE TITLE
Sample Load only works once.

### ISSUE THREAD

**Issue by Chaircrusher** [LomasModules/LomasModules#6]
If I instantiate an Advanced Sampler, load a sample, it works as expected. But if I click the load button a second time and select a different sample it keeps playing the first sample loaded.

**Comment by LomasModules** [comment]
The module loads a folder, not a sample, to select the sample inside the folder you have move the sample knob. 

Does that solve the problem?

**Comment by LomasModules** [comment]
The sampler loads the selected file on the open modal window.
