### ISSUE TITLE
Click, Even With Attack

### ISSUE THREAD

**Issue by Miserlou** [LomasModules/LomasModules#9]
Hey Lomas! Great modules!

I've noticed that Advanced Sampler has a click to it, as samples are being interrupted without any smooth mixing decay, etc. Would be great to use sampler as a drum machine if this click was removed! Thanks!

**Comment by Petervos2018** [comment]
Maybe related to : 
https://github.com/LomasModules/LomasModules/issues/7#issuecomment-527556868

**Comment by LomasModules** [comment]
This looks like normal behavior. If a sample is interrupted while is not at 0v it will make a click sound because of the discontinuity in voltage. Try play with the start and end points and envelope to mask the click. 

However I will look into it.

**Comment by Miserlou** [comment]
Ah, yes, that's what I assumed, but I think most hardware digital samplers
either have multiple alternating buffers or add a very very slight
release/attack to avoid this problem though

**Comment by LomasModules** [comment]
It could be because the envelope does not reset, dont go to 0v, when triggered, because the default vcv adsr works that way. I think I am going to change it so it resets like every other VST sampler.

**Comment by LomasModules** [comment]
I have implemented something to smooth some transitions. I can't have two buffers because the sampler is monophonic. Now when a sample is cut a small envelope is added to the signal to smooth the transion to 0v.

**Comment by Petervos2018** [comment]
Hi ~~Lomas~~ Guillermo I don't know where to begin...
Did you turn the EOC into a gate ? Why ? And why does it stay high for about 45 seconds. ?
I think you were on the right track with 1.0.8 but 1.0.8d is destroying all your hard work.
What can I do to help you ?

Greetings Peter.

**Comment by Miserlou** [comment]
Peter is savage.

**Comment by LomasModules** [comment]
Hey Peter.

The EOC thing is a bug. Is 45 seconds long because your sounds are sampled at 44100. It is supposed to be 1 ms but the math is wrong.

**Comment by Petervos2018** [comment]
Hey Guillermo

> The EOC thing is a bug. 

Cool, I wait for an update and test it, as you may have guessed I really like this sampler and I want to make it work.

Greetings Peter.

**Comment by LomasModules** [comment]
It's good to have people tell me about my mistakes. Belive or not 1/4 of my dev time is testing the modules. But sometimes I can't test everything. I have to look into what people call unit testing.

**Comment by Petervos2018** [comment]
Thanks for fixing the EOC thing in 1.0.9. :+1: 

Greetings Peter.
